---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dvwa-tls
  namespace: dvwa
spec:
  secretName: dvwa-tls
  privateKey:
    rotationPolicy: Always
  commonName: $DOMAIN_NAME
  dnsNames:
    - $DOMAIN_NAME
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
