---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: artifacts-tls
  namespace: artifacts
spec:
  secretName: artifacts-tls
  privateKey:
    rotationPolicy: Always
  commonName: ollama.40docs.com
  dnsNames:
    - ollama.40docs.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
