apiVersion: apps/v1
kind: Deployment
metadata:
  name: extractor
  namespace: extractor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: extractor
  template:
    metadata:
      labels:
        app: extractor
    spec:
      containers:
      - name: extractor
        image: ghcr.io/40docs/pptx_extractor:latest  # Image name (change as needed)
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: extractor-config
        resources:
          requests:
            memory: "512Mi"  # Requests 512MB of memory
            cpu: "500m"      # Requests 500 milliCPU (0.5 CPU core)
          limits:
            memory: "1Gi"    # Limits the container to 1Gi of memory
            cpu: "1"         # Limits the container to 1 CPU core
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3