---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: extractor-pvc
  namespace: extractor
  labels:
    app: extractor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-premium
  volumeMode: Filesystem
