apiVersion: v1
kind: Service
metadata:
  name: extractor
spec:
  selector:
    app: extractor
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 5000
  type: ClusterIP  # Set to LoadBalancer if you want external access
