apiVersion: v1
kind: Service
metadata:
  name: extractor
  namespace: extractor
  annotations: {
    "health-check-ctrl": "HLTHCK_HTTP"
  }
spec:
  selector:
    app: extractor
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

