---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: extractor-tls
  namespace: extractor
spec:
  secretName: extractor-tls
  privateKey:
    rotationPolicy: Always
  commonName: extractor.40docs.com
  dnsNames:
    - extractor.40docs.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
