---
name: artifacts-version
on:
  push:
    paths:
      - 'artifacts/**'
      - 'artifacts-dependencies/**'
  repository_dispatch:
    types: [artifacts-version]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions:
  id-token: write
  contents: write
jobs:
  artifacts-version:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          ref: main

      - name: Setup Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Process fqdn
        run: |
          export DOMAIN_NAME="${{ vars.OLLAMA_FQDN }}"
          envsubst < artifacts-dependencies/certificate.yaml > artifacts-dependencies/certificate.processed.yaml
          mv artifacts-dependencies/certificate.processed.yaml artifacts-dependencies/certificate.yaml
          envsubst < artifacts/HelmRelease.yaml > artifacts/HelmRelease.processed.yaml
          mv artifacts/HelmRelease.processed.yaml artifacts/HelmRelease.yaml

      - name: Commit and Push Changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Process Dispatch"
            git push -f origin main:artifacts-version
          fi
