---
name: dvwa-version
on:
  push:
    paths:
      - 'dvwa/**'
      - 'dvwa-dependencies/**'
  repository_dispatch:
    types: [dvwa-version]
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
permissions:
  id-token: write
  contents: write
jobs:
  dvwa-version:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: main

      - name: Setup Git Configuration
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Process fqdn
        run: |
          export DOMAIN_NAME="${{ vars.DVWA_FQDN }}"
          envsubst < dvwa-dependencies/certificate.yaml > dvwa-dependencies/certificate.processed.yaml
          mv dvwa-dependencies/certificate.processed.yaml dvwa-dependencies/certificate.yaml
          envsubst < dvwa/Ingress.yaml > dvwa/Ingress.processed.yaml
          mv dvwa/Ingress.processed.yaml dvwa/Ingress.yaml

      - name: Process production variables
        if: env.PRODUCTION_ENVIRONMENT == 'false'
        run: |
          sed -i '/HorizontalPodAutoscaler/Id' dvwa/kustomization.yaml
          yq eval -i ".spec.replicas = 1" "dvwa/Deployment.yaml"
          yq eval -i 'del(.spec.template.spec.affinity)' "dvwa/Deployment.yaml"
          yq eval -i 'del(.spec.strategy)' "dvwa/Deployment.yaml"
        env:
          PRODUCTION_ENVIRONMENT: ${{ vars.PRODUCTION_ENVIRONMENT }}

      - name: Commit and Push Changes
        run: |
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Process Dispatch"
            git push -f origin main:dvwa-version
          fi
